### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by MrColeyC** [jdrescher2006/OBDFish#3]
Your app requires libQt5Bluetooth.so.5, but doesn't include dependency to install.
Adding this to yaml Requires sorts this and automatically installs it.

```
# Runtime dependencies which are not automatically detected
 Requires:
   - sailfishsilica-qt5 >= 0.10.9 
   - qt5-qtconnectivity-qtbluetooth >= 5.2.0
```

**Comment by jdrescher2006** [comment]
Thanks for your advice.
I added this dependency in 0.91-2 and uploaded it to warehouse.
