### ISSUE TITLE
.../qt5-qtconnectivity-qtbluetooth-5.6.2+git0-1.4.2.arm7hl.rpm not found on media...jolla.../ 2.1.4.14/jolla

### ISSUE THREAD

**Issue by HeinrichGit** [jdrescher2006/OBDFish#6]
While trying to install it I got the above message ...

**Comment by jdrescher2006** [comment]
It works for me on my Oneplus X with SFOS 2.1.4.14. What phone do you use and what Sailfish version you have?

**Comment by jdrescher2006** [comment]
Also tested on J1 and XPERIA X, no problems.

**Comment by jdrescher2006** [comment]
Please try with new version on openrepos.
